### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by bjo81** [helpsterTee/FritzBoxSpectrumLogger#1]
I'm getting `[2021-11-02T12:44:20.622249] Login failed` - the box logs "wrong password", but logging in via Firefox works.

**Comment by helpsterTee** [comment]
I've just created a clean venv and tried on my box and it works on FritzOS 07.28. The requests library was missing, but that should have brought up a runtime error on your side and not wrong password (fixed in master btw).

Does your password contain quotation marks or backslash characters?

You can try setting up another user "System" -> "FritzBox-Benutzer" and try a password without special characters. In the options keep "Access from internet enabled" off, enable Settings access. I also have voice messages and smart home enabled, but I don't know if that's really neccessary.

And then, you can try using your internal router IP instead of the domain name, which may be overwritten when using a third party DNS that is not honoring local DNS lookups.

**Comment by bjo81** [comment]
Problem solved: The issue was caused by https://github.com/sberk42/fritzbox_exporter which tried to get information without authentication.

**Comment by helpsterTee** [comment]
Great that worked for you! 

Just out of curiosity: How does the session from this project become invalid when https://github.com/sberk42/fritzbox_exporter tries to access the API without authentication?

Is this because of rate-limiting the login and then we fail because our login is so close to the other project?

**Comment by bjo81** [comment]
It seems due to the rate limiting. The fritzbox_exporter logs:
`Nov 02 17:47:11 home prometheus-fritzbox-exporter[3768767]: Error loading data.lua for data.usbOverview.devices.*.partitions.0.usedStorageInBytes: To many failed logins, login blocked for 35 seconds`

I have attached a dump of the failed login of your SpectrumLogger:
[logger.dump.zip](https://github.com/helpsterTee/FritzBoxSpectrumLogger/files/7462605/logger.dump.zip)
